"Resource/UI/MainBuyMenu.res"
{
	"BuySubMenu_TER"
	{
		"ControlName"		"CCSBuyMenu_TER"
		"fieldName"		"BuySubMenu_TER"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"640"
		"tall"			"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"setTitleBarVisible"	"0"
	}
	
	"BaseBackground"
	{
		"ControlName" "ImagePanel"
		"fieldName" "BaseBackground"
		"xpos" "107"
		"ypos" "20"
		"zpos" "-10"
		"wide" "430"
		"tall" "450"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"autoResize" "0"
		"pinCorner" "0"
		"image" "buymenu/base"
	}


	"money"
	{
		"ControlName"		"Label"
		"fieldName"		"money"
		"xpos"		"200"
		"ypos"		"36"
		"wide"		"160"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#Cstrike_Select_Category"
		"textAlignment"		"west"
		"dull=text"		"0"
		"brighttext"	"1"
	}



	"allWeapon"
	{
		"ControlName"		"Label"
		"fieldName"		"allWeapon"
		"xpos"		"110"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"ALL"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"	"1"
	}

	"selectedWeapon"
	{
		"ControlName"		"Label"
		"fieldName"		"selectedWeapon"
		"xpos"		"293"
		"ypos"		"49"
		"wide"		"170"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Selected Weapon"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"	"1"
	}
	//top button section

//	"ButtonAllWeapon"
//	{
//		"ControlName"		"MouseOverPanelButton"
//		"fieldName"		"ButtonAllWeapon"
//		"xpos"		"30"
//		"ypos"		"50"
//		"wide"		"30"
//		"tall"		"20"
//		"autoResize"		"0"
//		"pinCorner"		"2"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		""
//		"textAlignment"		"center"
//		"dulltext"		"0"
//		"brighttext"		"0"		
//		"sound_armed" "ui/UI_Button_Hover.wav"
//		"sound_depressed" "ui/UI_Button_Click.wav"
//		"Command"		"Resource/UI/buymenu_pb/AllWeapon.res"
//		"Default"		"0"		
//	}
	"ButtonRifle"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"ButtonRifle"
		"xpos"		"138"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Pb_Rifles"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AllRifle.res"
		"Default"		"0"		
	}

	"ButtonSMG"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"ButtonSMG"
		"xpos"		"168"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Pb_SMG"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AllSMG.res"
		"Default"		"0"		
	}
	"ButtonSniper"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"ButtonSniper"
		"xpos"		"198"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Pb_Snipers"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AllSniper.res"
		"Default"		"0"		
	}
	"ButtonSecondary"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"ButtonSecondary"
		"xpos"		"228"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Pb_Pistols"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AllSecondary.res"
		"Default"		"0"		
	}
	"ButtonSG"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"ButtonSG"
		"xpos"		"257"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Pb_Shotguns"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AllSG.res"
		"Default"		"0"		
	}
	"ButtonEq"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"ButtonEq"
		"xpos"		"286"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Pb_Equipments"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AllEquipment.res"
		"Default"		"0"		
	}
	//baris 1
	"m1887"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"m1887"
		"xpos"		"123"
		"ypos"		"67"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"M1887"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/M1887GLOCKKNIFESMOKE.res"
		"Default"		"0"		
	}

	"PrimaryImage1"
	{
		"ControlName"	"ImagePanel"
		"xpos"			"123"
		"ypos"			"67"
		"zpos"			"-1"
		"wide"			"115"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"image"			"gfx/vgui/m1887"
		"scaleImage"	"1"	
	}	

	"<"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"<"
		"xpos"		"248"
		"ypos"		"67"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/M1887GLOCKKNIFESMOKE.res"
		"Default"		"0"		
	}
	"auga3"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"auga3"
		"xpos"		"263"
		"ypos"		"67"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"Aug A3"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		""
		"Default"		"0"		
	}
	"PrimaryImage2"
	{
		"ControlName" "ImagePanel"
		"fieldName" "PrimaryImage2"
		"zpos"			"-1"		
		"xpos"		"263"
		"ypos"		"67"
		"wide"		"115"
		"tall"		"50"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"autoResize" "0"
		"pinCorner" "0"
		"image" "gfx/vgui/auga3"
	}

	">"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		">"
		"xpos"		"378"
		"ypos"		"67"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/KRISSGLOCKKNIFESMOKE.res"
		"Default"		"0"		
	}
	"krisssvd"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"krisssvd"
		"xpos"		"403"
		"ypos"		"67"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"KRISS SVD"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"		
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/KRISSGLOCKKNIFESMOKE.res"
		"Default"		"0"		
	}

	"PrimaryImage3"
	{
		"ControlName"	"ImagePanel"
		"xpos"			"403"
		"ypos"			"67"
		"wide"			"115"
		"tall"			"50"
		"zpos"			"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"gfx/vgui/krisssvd"
		"scaleImage"	"1"	
	}	

	//baris 2

	"usp"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"usp45"
		"xpos"		"123"
		"ypos"		"125"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"USP-45"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AUGA3USPKNIFESMOKE.res"
		"Default"		"0"		
	}

	"PrimaryImage4"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"123"
		"ypos"		"125"
		"wide"		"115"
		"tall"		"50"
		"zpos"			"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"gfx/vgui/usp45"
		"scaleImage"	"1"	
	}	

	"<2"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"<2"
		"xpos"		"248"
		"ypos"		"125"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AUGA3USPKNIFESMOKE.res"
		"Default"		"0"		
	}
	"glock"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"glock"
		"xpos"		"263"
		"ypos"		"125"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"Glock-18"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		""
		"Default"		"0"		
	}
	"PrimaryImage5"
	{
		"ControlName" "ImagePanel"
		"fieldName" "PrimaryImage5"
		"xpos"		"263"
		"ypos"		"125"
		"wide"		"115"
		"tall"		"50"
		"zpos"		"-10"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"autoResize" "0"
		"pinCorner" "0"
		"image" "gfx/vgui/glock18"
	}

	">2"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		">2"
		"xpos"		"378"
		"ypos"		"125"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AUGA3ELITESKNIFESMOKE.res"
		"Default"		"0"		
	}
	"dualElites"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"dualElites"
		"xpos"		"403"
		"ypos"		"125"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Dual Elites"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AUGA3ELITESKNIFESMOKE.res"
		"Default"		"0"		
	}

	"PrimaryImage6"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"403"
		"ypos"		"125"
		"wide"		"115"
		"tall"		"50"
		"zpos"			"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"gfx/vgui/elites"
		"scaleImage"	"1"	
	}	

//baris 3

	"knife1"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"knife1"
		"xpos"		"123"
		"ypos"		"185"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_ter"
		"Default"		"0"		
	}

//	"PrimaryImage7"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"			"52"
//		"ypos"			"240"
//		"zpos"			"-1"
//		"wide"			"157"
//		"tall"			"72"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"gfx/vgui/flashbang"
//		"scaleImage"	"1"	
//	}	

	"<3"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"<3"
		"xpos"		"248"
		"ypos"		"185"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		""
		"Default"		"0"		
	}
	"knife2"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"knife2"
		"xpos"		"263"
		"ypos"		"185"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"Knife"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		""
		"Default"		"0"		
	}
	"PrimaryImage8"
	{
		"ControlName" "ImagePanel"
		"fieldName" "PrimaryImage8"
		"xpos"		"263"
		"ypos"		"185"
		"wide"		"115"
		"tall"		"50"
		"zpos" "-10"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"autoResize" "0"
		"pinCorner" "0"
		"image" "gfx/vgui/knife"
	}

	">3"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		">3"
		"xpos"		"378"
		"ypos"		"185"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		""
		"Default"		"0"		
	}
	"knife3"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"knife3"
		"xpos"		"403"
		"ypos"		"185"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		""
		"Default"		"0"		
	}

//	"PrimaryImage9"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"		"403"
//		"ypos"		"185"
//		"wide"		"115"
//		"tall"		"50"
//		"zpos"			"-1"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"gfx/vgui/elites"
//		"scaleImage"	"1"	
//	}	

//baris 4

	"grenade1"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"grenade1"
		"xpos"		"123"
		"ypos"		"245"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AK47GLOCKKNIFEFB.res"
		"Default"		"0"		
	}

//	"PrimaryImage10"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"		"123"
//		"ypos"		"245"
//		"wide"		"115"
//		"tall"		"50"
//		"zpos"			"-1"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"gfx/vgui/flashbang"
//		"scaleImage"	"1"	
//	}	

	"<4"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"<4"
		"xpos"		"248"
		"ypos"		"245"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AK47GLOCKKNIFEFB.res"
		"Default"		"0"		
	}
	"hegrenade"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"hegrenade"
		"xpos"		"263"
		"ypos"		"245"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"HE Grenade"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		""
		"Default"		"0"		
	}
	"PrimaryImage11"
	{
		"ControlName" "ImagePanel"
		"fieldName" "PrimaryImage11"
		"xpos"		"263"
		"ypos"		"245"
		"wide"		"115"
		"tall"		"50"
		"zpos" "-10"
		"visible" "1"
		"enabled" "0"
		"scaleImage" "1"
		"autoResize" "0"
		"pinCorner" "0"
		"image" "gfx/vgui/hegrenade"
	}

	">4"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		">4"
		"xpos"		"378"
		"ypos"		"245"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_ter"
		"Default"		"0"		
	}
	"grenade3"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"grenade3"
		"xpos"		"403"
		"ypos"		"245"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_ter"
		"Default"		"0"		
	}

//	"PrimaryImage12"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"		"403"
//		"ypos"		"245"
//		"wide"		"115"
//		"tall"		"50"
//		"zpos"			"-1"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"gfx/vgui/elites"
//		"scaleImage"	"1"	
//	}	


//baris 5
	"flashbang"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"flashbang"
		"xpos"		"123"
		"ypos"		"305"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Flashbang"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AUGA3GLOCKKNIFEFB.res"
		"Default"		"0"		
	}

	"PrimaryImage13"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"123"
		"ypos"		"305"
		"wide"		"115"
		"tall"		"50"
		"zpos"			"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"gfx/vgui/flashbang"
		"scaleImage"	"1"	
	}	

	"<5"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"<5"
		"xpos"		"248"
		"ypos"		"305"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_pb/AUGA3GLOCKKNIFEFB.res"
		"Default"		"0"		
	}
	"smokegrenade"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"smokegrenade"
		"xpos"		"263"
		"ypos"		"305"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"Smoke Grenade"
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		""
		"Default"		"0"		
	}
	"PrimaryImage14"
	{
		"ControlName" "ImagePanel"
		"fieldName" "PrimaryImage14"
		"xpos"		"263"
		"ypos"		"305"
		"wide"		"115"
		"tall"		"50"
		"zpos" "-10"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"autoResize" "0"
		"pinCorner" "0"
		"image" "gfx/vgui/smokegrenade"
	}

	">5"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		">5"
		"xpos"		"378"
		"ypos"		"305"
		"wide"		"15"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_ter"
		"Default"		"0"		
	}
	"special3"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"special3"
		"xpos"		"403"
		"ypos"		"305"
		"wide"		"115"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"north"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Click.wav"
		"Command"		"Resource/UI/buymenu_ter"
		"Default"		"0"		
	}

//	"PrimaryImage15"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"		"403"
//		"ypos"		"305"
//		"wide"		"115"
//		"tall"		"50"
//		"zpos"			"-1"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"gfx/vgui/elites"
//		"scaleImage"	"1"	
//	}	


//baris 6
//	"acc1"
//	{
//		"ControlName"		"MouseOverPanelButton"
//		"fieldName"		"acc1"
//		"xpos"		"123"
//		"ypos"		"365"
//		"wide"		"115"
//		"tall"		"50"
//		"autoResize"		"0"
//		"pinCorner"		"2"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		" "
//		"textAlignment"		"north"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"sound_armed" "ui/UI_Button_Hover.wav"
//		"sound_depressed" "ui/UI_Button_Click.wav"
//		"Command"		"Resource/UI/buymenu_pb/AK47GLOCKKNIFEFB.res"
//		"Default"		"0"		
//	}
//
//	"PrimaryImage16"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"		"123"
//		"ypos"		"365"
//		"wide"		"115"
//		"tall"		"50"
//		"zpos"			"-1"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"gfx/vgui/flashbang"
//		"scaleImage"	"1"	
//	}	
//
//	"<6"
//	{
//		"ControlName"		"MouseOverPanelButton"
//		"fieldName"		"<6"
//		"xpos"		"248"
//		"ypos"		"365"
//		"wide"		"15"
//		"tall"		"50"
//		"autoResize"		"0"
//		"pinCorner"		"2"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		" "
//		"textAlignment"		"west"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"sound_armed" "ui/UI_Button_Hover.wav"
//		"sound_depressed" "ui/UI_Button_Click.wav"
//		"Command"		"Resource/UI/buymenu_pb/AK47GLOCKKNIFEFB.res"
//		"Default"		"0"		
//	}
//	"acc2"
//	{
//		"ControlName"		"MouseOverPanelButton"
//		"fieldName"		"acc2"
//		"xpos"		"263"
//		"ypos"		"365"
//		"wide"		"115"
//		"tall"		"50"
//		"autoResize"		"0"
//		"pinCorner"		"2"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		" "
//		"textAlignment"		"north"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"sound_armed" "ui/UI_Button_Hover.wav"
//		"sound_depressed" "ui/UI_Button_Click.wav"
//		"Command"		""
//		"Default"		"0"		
//	}
//	"PrimaryImage17"
//	{
//		"ControlName" "ImagePanel"
//		"fieldName" "PrimaryImage17"
//		"xpos"		"263"
//		"ypos"		"365"
//		"wide"		"115"
//		"tall"		"50"
//		"zpos" "-10"
//		"visible" "1"
//		"enabled" "1"
//		"scaleImage" "1"
//		"autoResize" "0"
//		"pinCorner" "0"
//		"image" "gfx/vgui/smokegrenade"
//	}
//
//	">6"
//	{
//		"ControlName"		"MouseOverPanelButton"
//		"fieldName"		">6"
//		"xpos"		"378"
//		"ypos"		"365"
//		"wide"		"15"
//		"tall"		"50"
//		"autoResize"		"0"
//		"pinCorner"		"2"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		" "
//		"textAlignment"		"west"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"sound_armed" "ui/UI_Button_Hover.wav"
//		"sound_depressed" "ui/UI_Button_Click.wav"
//		"Command"		"Resource/UI/buymenu_ter"
//		"Default"		"0"		
//	}
//	"acc3"
//	{
//		"ControlName"		"MouseOverPanelButton"
//		"fieldName"		"acc3"
//		"xpos"		"403"
//		"ypos"		"365"
//		"wide"		"115"
//		"tall"		"50"
//		"autoResize"		"0"
//		"pinCorner"		"2"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		" "
//		"textAlignment"		"north"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"sound_armed" "ui/UI_Button_Hover.wav"
//		"sound_depressed" "ui/UI_Button_Click.wav"
//		"Command"		"Resource/UI/buymenu_ter"
//		"Default"		"0"		
//	}
//
//	"PrimaryImage18"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"		"403"
//		"ypos"		"305"
//		"wide"		"115"
//		"tall"		"50"
//		"zpos"			"-1"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"gfx/vgui/elites"
//		"scaleImage"	"1"	
//	}	


	"OKButton"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"OKButton"
		"xpos"		"260"
		"ypos"		"430"
		"wide"		"60"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"OK"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Equip.wav"
		"Command"		"sm_current_primary auga3; sm_current_secondary glock; sm_current_grenade 1; sm_current_flashbang 0; sm_current_smokegrenade 1"
		"Default"		"1"
	}

	"CancelButton"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"CancelButton"
		"xpos"		"330"
		"ypos"		"430"
		"wide"		"60"
		"tall"		"30"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Close"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"sound_armed" "ui/UI_Button_Hover.wav"
		"sound_depressed" "ui/UI_Button_Cancel.wav"
		"Command"		"vguicancel"
		"Default"		"1"
	}
	"BuyPresetEditButton"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"BuyPresetEditButton"
		"xpos"		"460"
		"ypos"		"340"
		"wide"		"120"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyPresetEditPresetsButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"buy_preset_edit reopen"
		"Default"		"0"
	}
	"loadoutPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"loadoutPanel"
		"xpos"		"1000"
		"ypos"		"102"
		"wide"		"0"
		"tall"		"0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
	}

	//decoration section
	"selectedWeaponImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"263"
		"ypos"		"51"
		"zpos"		"-1"
		"wide"		"115"
		"tall"		"15"		
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/selectedWeapon"
		"scaleImage"	"1"	
	}
	"leftArrowImage1"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"248"
		"ypos"		"67"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/leftArrow"
		"scaleImage"	"1"	
	}
	"rightArrowImage1"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"378"
		"ypos"		"67"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/rightArrow"
		"scaleImage"	"1"	
	}
	"leftArrowImage2"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"248"
		"ypos"		"125"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/leftArrow"
		"scaleImage"	"1"	
	}
	"rightArrowImage2"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"378"
		"ypos"		"125"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/rightArrow"
		"scaleImage"	"1"	
	}
	"leftArrowImage3"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"248"
		"ypos"		"185"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/leftArrow"
		"scaleImage"	"1"	
	}
	"rightArrowImage3"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"378"
		"ypos"		"185"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/rightArrow"
		"scaleImage"	"1"	
	}
	"leftArrowImage4"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"248"
		"ypos"		"245"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/leftArrow"
		"scaleImage"	"1"	
	}
	"rightArrowImage4"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"378"
		"ypos"		"245"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/rightArrow"
		"scaleImage"	"1"	
	}
	"leftArrowImage5"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"248"
		"ypos"		"305"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/leftArrow"
		"scaleImage"	"1"	
	}
	"rightArrowImage5"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"378"
		"ypos"		"305"
		"wide"		"15"
		"tall"		"50"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/rightArrow"
		"scaleImage"	"1"	
	}
//	"leftArrowImage6"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"		"248"
//		"ypos"		"365"
//		"wide"		"15"
//		"tall"		"50"
//		"zpos"		"-1"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"buymenu/leftArrow"
//		"scaleImage"	"1"	
//	}
//	"rightArrowImage6"
//	{
//		"ControlName"	"ImagePanel"
//		"xpos"		"378"
//		"ypos"		"365"
//		"wide"		"15"
//		"tall"		"50"
//		"zpos"		"-1"
//		"visible"		"1"
//		"enabled"		"1"
//		"image"			"buymenu/rightArrow"
//		"scaleImage"	"1"	
//	}
	"OKImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"260"
		"ypos"		"430"
		"wide"		"60"
		"tall"		"30"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/baseButton"
		"scaleImage"	"1"	
	}	
	"CloseImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"330"
		"ypos"		"430"
		"wide"		"60"
		"tall"		"30"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/baseButton"
		"scaleImage"	"1"	
	}
	"AllWeaponImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"110"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/buttonPlainActive"
		"scaleImage"	"1"	
	}
	"ButtonRifleImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"138"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/buttonRifleDeactive"
		"scaleImage"	"1"	
	}
	"ButtonSMGImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"168"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/buttonSMGDeactive"
		"scaleImage"	"1"	
	}
	"ButtonSniperImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"198"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/buttonSniperDeactive"
		"scaleImage"	"1"	
	}
	"ButtonSecondaryImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"228"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/buttonSecondaryDeactive"
		"scaleImage"	"1"	
	}
	"ButtonSGImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"257"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/buttonSGDeactive"
		"scaleImage"	"1"	
	}
	"ButtonEqImage"
	{
		"ControlName"	"ImagePanel"
		"xpos"		"286"
		"ypos"		"25"
		"wide"		"30"
		"tall"		"20"
		"zpos"		"-1"
		"visible"		"1"
		"enabled"		"1"
		"image"			"buymenu/buttonEqDeactive"
		"scaleImage"	"1"	
	}



}
